### ISSUE TITLE
Private IDG Interface not working

### ISSUE THREAD

**Issue by ecibrian** [chembl/IDG#104]
I cannot access the private IDG interface you set for me last week.

**Comment by mnowotka** [comment]
Hi Elena,

As you can see in a group calendar I'm currently in Erlangen, Germany and I don't have an immediate access to the intranet. I can have a quick look later today.

However can you tell me what do you mean by saying "you cannot access it"? Does it mean the interface is down or it's up but you can't log in?

If the interface is up, you can probably ask Anna to create an account for you.
If the interface is down, I'm afraid this can be related to the nfs maintenance that was due to finish last Thursday but it's still in progress as far as I know.

**Comment by agaulton** [comment]
Hi Michal,
I cannot access it either - http://sark.ebi.ac.uk:7001/idg just hangs and then gives me a white page, no login prompt and no error message. The main version on 8484 works fine.
Let me know if there is anything I can do to restart it etc, but not super urgent - just that Elena wants to have a play with it (and not with the production one)…
Anna

**Comment by mnowotka** [comment]
Hi Anna,
I have my secureID token in hotel so I can go during the lunch break and try to restart it. I don't remember where the development version is deployed to, it might be on nfs and this can be the source of the problem.

**Comment by agaulton** [comment]
I’m sure it can wait til later, so don’t rush back if you have other stuff to do
A

**Comment by ecibrian** [comment]
Hi Michal, I can wait, no need to rush.

Thanks

Elena

**Comment by mnowotka** [comment]
OK, it's restarted now, there was some nfs glitch but it's fine after restarting, sorry about that.

**Comment by ecibrian** [comment]
Thank you!
