### ISSUE TITLE
should we make company code unique?!

### ISSUE THREAD

**Issue by revajk** [chembl/IDG#44]
Anneli, The company codes in the excel spreadsheet are they unique for a particular company? Should I  make it unique to avoid future problems?

**Comment by Anneli15** [comment]
The company codes are unique to a certain compound and also company except that the compound will often move/be sold to another company and get new names/codes. So, code is unique to a company (like PF12345 is a Pfizer-named compound) but compound may have more than one code and more than one company associated with it. However, there won't be (shouldn't be) 2 compounds with exactly the same code. If I have the same compound code in 2 different spreadsheet it is only because I can't remember (and have not checked) that I have already added the compound in another spreadsheet. This would only happen if say a compound targets a GPCR and an ion channel or kinase i.e. can appear in more than 1 spreadsheet. So the compound should not be duplicated in the data base but alert and new target can be added (if not already in the system).

**Comment by Anneli15** [comment]
Sorry if that was a long and confusing answer, let me know if you don't understand what I mean...

**Comment by revajk** [comment]
OKIE that makes sense. At the moment you can add more targets for a  individual compound. It can be a GPCR, ion channel , NR or KI. So, it does makes sense to make it unique in the molecule dictionary level.

**Comment by mnowotka** [comment]
Is this fixed?

**Comment by Anneli15** [comment]
Yes, should be OK. Not sure if this was really a problem. I have been able to add several targets to a compound.

**Comment by revajk** [comment]
Yes, but there are more than one record for a molecule at the moment. Cleaning up.

**Comment by Anneli15** [comment]
OK, I see what you mean now. The same molecule has been loaded twice because the code hasn't been set as unique. There probably aren't that many or?

**Comment by revajk** [comment]
there were few (20s ) but main thing is I should relate their data to one before removing the other. taking bit of time.

**Comment by Anneli15** [comment]
Ok, just let me know if you need help with editing these
