### ISSUE TITLE
Chembl look up

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#56]
There seem to be a problem with the look up and loaded data regarding the prodrug/black box status. Thought it was odd that Aspirin came up as having both black box warning and being a prodrug so i checked.... 
Looks like all the compounds in the molecular dictionary have a positive prodrug status which is not the case (very few are). Please can you check this bug?

**Comment by Anneli15** [comment]
Aspirin has neither in chembl

**Comment by revajk** [comment]
Okie! Going through the bug. I can't seem to find a problem with the code. But NullBoolean is not returning False from custom save. Seems like a known issue. http://stackoverflow.com/questions/16291315/django-nullbooleanfield-wont-retain-false-value-from-custom-save-method. Changing them to CharField seems to  work fine. But we lose all the 'Unknown'. Still working on this will let you know how it goes. 
@mnowotka  if you have any other suggestions  do let me know. Thanks

**Comment by revajk** [comment]
Got it. It takes only True or false (https://github.com/django/django/blob/master/django/db/models/fields/__init__.py#L2039). No 0, 1, 'YES' , 'No', 'True', 'False'. I will deploy this now. I don't think we have to stop the production server @Anneli15 . Since there is no change in the data.

**Comment by mnowotka** [comment]
Yes, I have a couple of suggestions. First of all it would be useful to check if you have correct values. To check this I would suggest writing a unit test. Then IF you know for sure that you have correct values, you pass those correct values to Django and Django is ignoring them, I would create a minimal test case and report the bug going through the steps described here: https://docs.djangoproject.com/en/1.8/internals/contributing/bugs-and-features/. If the bug is confirmed, I'm sure one of the Django core developers will propose some sensible solution. You may also try our own implementation of NullBoolean field: ChemblNullableBooleanField (https://github.com/chembl/chembl_core_db/blob/master/chembl_core_db/db/customFields.py) from the `chembl_core_db` package but I can't guarantee it will be compatible with Django version used in IDG. I know that Andrew Stretton has his own fork he made compatible with lasts Django versions: https://github.com/thesgc/chembl_core_db.

**Comment by mnowotka** [comment]
OK, so was it a know issue or a bug in IDG code?

**Comment by revajk** [comment]
Well, I was getting the right value from the CHEMBL and passing the right value. IT was later realisation that NullBoolean takes only True or False.

**Comment by revajk** [comment]
Anneli, Could you confirm that the Prodrug and Black box warning are all fixed now.

**Comment by Anneli15** [comment]
Yes, seems to work fine, thanks.
