### ISSUE TITLE
Create New molecule dictionary tab

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#9]
![screen shot 2015-06-11 at 3 00 04 pm](https://cloud.githubusercontent.com/assets/12811998/8108806/aeb0371e-104a-11e5-93f5-6de6d924f07e.png)

In Status field: I added "Discontinued" but shows up as "StatusType object"?

**Comment by mnowotka** [comment]
@Anneli15 , thank you for reporting this. @revajk , this is because the our models don't have `__unicode__()` and `__str__()` functions defined. You can read more here: https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display, please add them for every model and release to sark.

**Comment by mnowotka** [comment]
I've just noticed that the title of this issue (#9) is the same as https://github.com/chembl/IDG/issues/6, @Anneli15  can you be more specific next time when creating issues, so it's easier for us to distinguish between them?

**Comment by revajk** [comment]
Done. Should be available as expected.
