### ISSUE TITLE
Moelcule dictionary

### ISSUE THREAD

**Issue by Anneli15** [chembl/IDG#99]
If there is no drug type. the entry can't be edited or at least i don't know how to do this? I deleted the drug type as the compound is not a small molecule in Chembl but a "Natural Product" which wasn't accepted as a "correct entry".

![screen shot 2015-12-16 at 9 50 40 am](https://cloud.githubusercontent.com/assets/12811998/11837762/d52f0d10-a3da-11e5-9936-5cbc3bd905fd.png)

**Comment by Anneli15** [comment]
A drug type "Natural Product" needs to be added into IDG, exists in Chembl but is not accepted in IDG. There are several drugs that needs this type annotated. They now have "Small molecule" as type but this does not reflect Chembl entries. Also the -4 phases are back in the database, I correct them as I come across but there seem to be quite a lot of old issues that have occurred again since last deployment (or previous ones, haven't necessarily checked all every time the system was been updated).

**Comment by Anneli15** [comment]
Also the "yes" as default prodrug status problem seem to be back.....

**Comment by mnowotka** [comment]
I can explain why you are getting this error. When you add or edit compound with CHEMBL_ID defined, the data is verified with ChEMBL. The "drug_type" field is compared with "molecule_type" in ChEMBL. (Now I don't know why "drug_type" in IDG are considered to be equivalent with "molecule_type" in ChEMBL, I would have to ask Riva, I just say what I see in the code). Now for compound "CHEMBL1200686" the molecule_type is set to "Small molecule" in ChEMBL so you can't put anything else here. "Natural Product" is not a "drug type" in ChEMBL, simply because there is no such a column like "drug type" in ChEMBL. There is only a flag indicating if the compound is a "Natural product" or not but it has nothing to do with "molecule type" to which "drug type" is mapped. I know it may sound complicated but I'm happy to discuss it in person.

**Comment by Anneli15** [comment]
OK, that's fine, will just leave as small molecule. What about issue 97 and "Highest phase"?
